export const NOT_FOUND = {
  MESSAGE: 'NOT_FOUND',
  DESCRIPTION: {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  },
};

export const NOT_AUTHORIZED = {
  MESSAGE: 'NOT_AUTHORIZED',
  DESCRIPTION: {
    CREDENTIALS_NOT_FOUND: 'CREDENTIALS_NOT_FOUND',
    CREDENTIALS_EXPIRED: 'CREDENTIALS_EXPIRED',
    ACCESS_TOKEN_REVOKED: 'ACCESS_TOKEN_REVOKED',
    REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
    WRONG_PASSWORD: 'WRONG_PASSWORD',
    INVALID_JWT_FROM_GOOGLE: 'INVALID_JWT_FROM_GOOGLE',
    INVALID_JWT: 'INVALID_JWT',
  },
};
